### ISSUE TITLE
Can't run the bot

### ISSUE THREAD

**Issue by pikopie** [Khaazz/Cross-Server-Bot#1] opened 2019-03-15 06:19 UTC
Hi,

I want to link two channels (say Channel A and Channel B) within the same discord server.  But I can't seem to run the bot properly:

1. Do I need to create a webhook for each of Channel A and Channel B?
2. How do I get the "whID": "232323" and "whToken": "webhookToken2323"?

Thanks.

**Comment by VoidNulll** [comment] 2019-03-15 07:05
1) Yes, you need to create a webhook for both channels.
2. You take the token & id from the token url you get when creating (or editing) the token. A webhook url looks something like this: `https://ptb.discordapp.com/api/webhooks/1234/5ac6gf7ty8`.
After `webhooks/` would be your token id (1234). After the id (plus slash) comes the token (5ac6gf7ty8)

**Comment by pikopie** [comment] 2019-03-15 07:40
That's what exactly what I've done.  I have created a webhook in both channels, and updated the "whID": "232323" and "whToken": "webhookToken2323" for both channels accordingly.

**Comment by pikopie** [comment] 2019-03-15 07:42
Do you want if I discuss with you in discord?

**Comment by VoidNulll** [comment] 2019-03-15 07:43
So, it works, yes?

**Comment by pikopie** [comment] 2019-03-15 07:47
nope, the bot goes online, and the message "Bot Ready - Cross Server system operational!" is posted in both channels.  But after that, it doesn't copy messages typed in Channel A, and paste it in Channel B.

**Comment by VoidNulll** [comment] 2019-03-15 07:52
Do you get any error messages in the console?

**Comment by pikopie** [comment] 2019-03-15 07:55
No, there is no error message in the console.  See picture below.

![image](https://user-images.githubusercontent.com/48026548/54416551-af864b80-473a-11e9-8fea-d293b5804103.png)

**Comment by VoidNulll** [comment] 2019-03-15 07:58
Interesting.

**Comment by VoidNulll** [comment] 2019-03-15 08:06
Perhaps check that the bot has read message permissions for both those channels?

**Comment by Khaazz** [comment] 2019-03-15 08:08
Make sure the bot has readMessages perms in all channels linked. 
If the issue get resolved after this notify us here. Otherwise i suggest coming in discord directly, it will be easier to resolve the issue.

**Comment by pikopie** [comment] 2019-03-15 08:09
I gave the bot all permissions, even manage message permissions. But it still doesn't work.

Can I have the link to your discord server, or your discord ID?  thanks

**Comment by VoidNulll** [comment] 2019-03-15 08:12
[Join us here!](https://discord.gg/QZ6B5US)

**Comment by Khaazz** [comment] 2019-03-15 09:09
The issue was caused by the two channels linked being in the same server.
This is not achievable at the moment as this was not the primary design of this bot.
Support for this will be added in further version as the usability of it is proven to be useful.

Closing the issue.

**Closed** 2019-03-15 09:10 UTC
Labels: enhancement, not a bug

**Comment by Khaazz** [comment] 2019-03-21 22:05
Support for this was officially added in v2.
